version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"

  backend:
    build: ./services/album_service/app
    volumes:
      - ./services/album_service:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/album_db
    ports:
      - "8000:8000"
    depends_on:
      - db


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "3000:3000"

volumes:
  postgres_data:
