"""add description field to albums

Revision ID: f982b9e9ab39
Revises: d460f8369840
Create Date: 2024-10-03 03:27:45.434785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f982b9e9ab39'
down_revision: Union[str, None] = 'd460f8369840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'description')
    # ### end Alembic commands ###
